version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app
    command: sh -c "yarn && yarn docker"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./.docker/api/Dockerfile
    tty: true
    ports:
      - "8082:8082"
    volumes:
      - ./api:/go/src/api
    command: go run main.go
    depends_on:
      - mysql
  mysql:
    build: ./.docker/mysql/
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=golang
    ports:
      - "3306:3306"
    container_name: mysql-container-jwt
